# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Depbisect < Formula
  desc "git bisect, but for dependency updates"
  homepage "https://github.com/skyneticist/depbisect"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyneticist/depbisect/releases/download/v0.1.3/depbisect_0.1.3_darwin_amd64.tar.gz"
      sha256 "6ddc7b9eb24afa36d665a90c2009d8b3c3d32041d0d36a634c33d91d0b7e9df3"

      define_method(:install) do
        bin.install "depbisect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyneticist/depbisect/releases/download/v0.1.3/depbisect_0.1.3_darwin_arm64.tar.gz"
      sha256 "f8d2722b9bcc3165806659dd74fa2ce9bc10d363a5c77ce594e2e119e3e4de17"

      define_method(:install) do
        bin.install "depbisect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyneticist/depbisect/releases/download/v0.1.3/depbisect_0.1.3_linux_amd64.tar.gz"
      sha256 "8ed93e6cab3eae67db6af8f168ce9f364e49805eda20ba8c2a963ab58344803a"
      define_method(:install) do
        bin.install "depbisect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyneticist/depbisect/releases/download/v0.1.3/depbisect_0.1.3_linux_arm64.tar.gz"
      sha256 "582d1acd1a3edf8845494b04a96cec038ef686e0111191af6f7fe08c2292ebc5"
      define_method(:install) do
        bin.install "depbisect"
      end
    end
  end
end
