# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Depbisect < Formula
  desc "git bisect, but for dependency updates"
  homepage "https://github.com/skyneticist/depbisect"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyneticist/depbisect/releases/download/v0.1.5/depbisect_0.1.5_darwin_amd64.tar.gz"
      sha256 "30ab7511273834682219a3e377d1c9e8ac27a32a1318080232458b9b2d1a71be"

      define_method(:install) do
        bin.install "depbisect"
        generate_completions_from_executable(bin/"depbisect", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyneticist/depbisect/releases/download/v0.1.5/depbisect_0.1.5_darwin_arm64.tar.gz"
      sha256 "beefd54bb018e5487df33da553ffc413d9ef8f1a2641cf7d71d4c091a75677b5"

      define_method(:install) do
        bin.install "depbisect"
        generate_completions_from_executable(bin/"depbisect", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyneticist/depbisect/releases/download/v0.1.5/depbisect_0.1.5_linux_amd64.tar.gz"
      sha256 "a3c114d5ac4c083862b9038033d4776df9e0bc977341997cbfd41ebbc617fe8e"
      define_method(:install) do
        bin.install "depbisect"
        generate_completions_from_executable(bin/"depbisect", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyneticist/depbisect/releases/download/v0.1.5/depbisect_0.1.5_linux_arm64.tar.gz"
      sha256 "e800e7e1c3f19776179bfb22c920712e84561ae79a496f6dedb747f33da5f26b"
      define_method(:install) do
        bin.install "depbisect"
        generate_completions_from_executable(bin/"depbisect", "completion", shells: [:bash, :zsh])
      end
    end
  end
end
